//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estagiei.Models.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbUser
    {
        public int userId { get; set; }

        [Display(Name = "Nome")]
        public string userName { get; set; }

        [Display(Name = "Documento")]
        public string userDocument { get; set; }

        [Display(Name = "E-mail")]
        public string userEmail { get; set; }

        [Display(Name = "Telefone")]
        public string userPhone { get; set; }
    }
}
